### PR TITLE
update compat bounds for ArrayInterface and Static; remove unused dependency ThreadingUtilities

### PR DESCRIPTION
**Pull request by ranocha**
I collected the compat bounds updates of #40 and #41 in this PR. I also removed ThreadingUtilities.jl as direct dependency since it never appeared except in `Project.toml`.

I also disabled ambiguities testing via Auqa.jl since it results in 21 method ambiguities from ForwardDiff.jl and ChainRulesCore.jl.

Closes #37, closes #38, closes #39, closes #40, closes #41, closes #43, closes #44, closes #45

### CODE REVIEW

**Comment by chriselrod** [comment]
```julia
  StackOverflowError:
  Stacktrace:
       [1] PtrArray
         @ ~/.julia/packages/StrideArraysCore/TzFER/src/ptr_array.jl:7 [inlined]
       [2] PtrArray
         @ ~/.julia/packages/StrideArraysCore/TzFER/src/ptr_array.jl:11 [inlined]
       [3] PtrArray
         @ ~/.julia/packages/StrideArraysCore/TzFER/src/ptr_array.jl:24 [inlined]
       [4] maybe_ptr_array
         @ ~/.julia/packages/StrideArraysCore/TzFER/src/stridearray.jl:150 [inlined]
       [5] maybe_ptr_array
         @ ~/.julia/packages/StrideArraysCore/TzFER/src/stridearray.jl:149 [inlined]
       [6] mapreduce(f::typeof(norm), op::typeof(max), A::PtrArray{Tuple{Int64, Int64}, (true, false), Float64, 2, 1, 0, (1, 2), Tuple{StaticInt{8}, StaticInt{640}}, Tuple{StaticInt{1}, StaticInt{1}}})
         @ StrideArrays ~/work/StrideArrays.jl/StrideArrays.jl/src/miscellaneous.jl:31
```
Probably a problem in StrideArraysCore?

**Comment by ranocha** [comment]
This happens only on Julia nightly, doesn't it?

**Comment by ranocha** [comment]
MWE using Julia v1.8.0-beta1:
```julia
julia> using StrideArrays

julia> A = @StrideArray rand(10, 10); A_ptr = view(A, 1:5, 1:5)
5×5 StrideArray{Tuple{Int64, Int64}, (true, false), Float64, 2, 1, 0, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}, StrideArraysCore.StaticStrideArray{Tuple{StaticInt{10}, StaticInt{10}}, (true, true), Float64, 2, 1, 0, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}, 100}}:
 0.628102  0.400895  0.170133   0.507153  0.709167
 0.134677  0.26607   0.0299581  0.735177  0.957184
 0.679169  0.539174  0.450646   0.616162  0.504812
 0.199461  0.929504  0.412679   0.428801  0.183159
 0.199211  0.719763  0.30123    0.197397  0.750064

julia> mapreduce(abs2, max, A_ptr)
ERROR: StackOverflowError:
Stacktrace:
     [1] PtrArray
       @ ~/.julia/packages/StrideArraysCore/TzFER/src/ptr_array.jl:7 [inlined]
     [2] PtrArray
       @ ~/.julia/packages/StrideArraysCore/TzFER/src/ptr_array.jl:11 [inlined]
     [3] PtrArray
       @ ~/.julia/packages/StrideArraysCore/TzFER/src/ptr_array.jl:24 [inlined]
     [4] maybe_ptr_array
       @ ~/.julia/packages/StrideArraysCore/TzFER/src/stridearray.jl:150 [inlined]
     [5] maybe_ptr_array
       @ ~/.julia/packages/StrideArraysCore/TzFER/src/stridearray.jl:149 [inlined]
     [6] mapreduce(f::typeof(abs2), op::typeof(max), A::PtrArray{Tuple{Int64, Int64}, (true, false), Float64, 2, 1, 0, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}})
       @ StrideArrays ~/.julia/dev/StrideArrays/src/miscellaneous.jl:31
     [7] vmapreduce(::typeof(abs2), ::typeof(max), ::PtrArray{Tuple{Int64, Int64}, (true, false), Float64, 2, 1, 0, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}})
       @ LoopVectorization ~/.julia/packages/LoopVectorization/wLMFa/src/simdfunctionals/mapreduce.jl:37
--- the last 2 lines are repeated 39990 more times ---
 [79988] mapreduce(f::typeof(abs2), op::typeof(max), A::PtrArray{Tuple{Int64, Int64}, (true, false), Float64, 2, 1, 0, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}})
       @ StrideArrays ~/.julia/dev/StrideArrays/src/miscellaneous.jl:31
```

**Comment by ranocha** [comment]
This also happens on Julia v1.7.2 for me.

**Comment by ranocha** [comment]
Any good idea how to break this cycle? Maybe it's too late over here but I do not see a good way to override `Base.mapreduce` for general `AbstractStrideArray`s while keeping `Base.mapreduce` available for non-dense `AbstractStrideArray`s. Does any of the type parameters of `AbstractStrideArray{S,D,T,N,C,B,R,X,O}` tell us whether it's `all_dense`?

**Comment by chriselrod** [comment]
Not exactly elegant, but a lazy workaround:
https://github.com/chriselrod/StrideArrays.jl/pull/43

**Comment by chriselrod** [comment]
All tests passed in #43 (which only tried to fix the bug blocking this), except for the no-ambiguities check which found one with `map` and `StaticArray`s.
Feel free to merge #43 into this and just disable all ambiguity checks as you do here, and I can merge, and then address that separate issue later.

**Comment by ranocha** [comment]
Sounds good to me :+1: I don't have merge right but you can go ahead

**Comment by ranocha** [comment]
@chriselrod I merged your PR #43 manually into this PR. Let's see whether CI passes this time

**Comment by chriselrod** [comment]
> Sounds good to me 👍 I don't have merge right but you can go ahead

You shouldn't need that.
`git merge origin/avoidstackoverflow`

**Comment by ranocha** [comment]
:+1: 

> You shouldn't need that. `git merge origin/avoidstackoverflow`

That's what I meant with

> I merged your PR #43 manually into this PR. Let's see whether CI passes this time

**Pull request merged**
