### PR TITLE
Separate core

### PR DESCRIPTION
**Pull request by chriselrod**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Looks like you need a compat entry for StrideArraysCore.

**Comment by chriselrod** [comment]
Yeah.
I also fixed the error in `log(::VecUnroll{N,1,T,T})` locally.

**Comment by DilumAluthge** [comment]
There's also a `MethodError: no method matching vnot(::Bool)`.

**Comment by DilumAluthge** [comment]
Good thing CI is working again 😂

**Comment by chriselrod** [comment]
That was the `log` error.

It also isn't working again. CI was disabled for JuliaSIMD, not for chriselrod.

**Comment by DilumAluthge** [comment]
Ohhh I didn't realize this repo was on `chriselrod`.

**Comment by chriselrod** [comment]
Maybe I'll transfer it, but definitely not right now lol
Something like JuliaArrays may also make more sense than JuliaSIMD anyway.

**Pull request merged**
