### PR TITLE
Factored out threading utils.

### PR DESCRIPTION
**Pull request by chriselrod**
Merge after [ThreadingUtilities.jl](https://github.com/JuliaRegistries/General/pull/28163) is registered.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
> Merge after [ThreadingUtilities.jl](https://github.com/JuliaRegistries/General/pull/28163) is registered.

Registered.

**Comment by DilumAluthge** [comment]
The test failures in this PR will be fixed in ThreadingUtilities version 0.1.1.

**Comment by chriselrod** [comment]
I'll probably merge this then just because, but after Octavian merges I'll just switch to that.

**Comment by DilumAluthge** [comment]
@chriselrod Bump the compat for ThreadingUtilities to 0.2?

**Comment by chriselrod** [comment]
> @chriselrod Bump the compat for ThreadingUtilities to 0.2?

That was a breaking change. Now that Octavian 0.2 is out, I'll update this PR to also make that transition.

**Pull request merged**
